### ISSUE TITLE
LaTeX-Problem: scrlayer-scrpage-Paket fehlt // scrlayer-scrpage-packet is missing

### ISSUE THREAD

**Issue by Nos-** [genericFJS/htw#2]
Folgende Fehlermeldung bekomme ich beim Versuch ein beliebiges LaTeX-Dokument aus dem Repo zu bauen:

        File `scrlayer-scrpage.sty' not found.

Und das obwohl ich _TeX-Live Full_ installiert habe ;-)

Ich werde mich mal auf www.CTAN.org und bei der Dresdner [(La)TeX-User-Group](http://tug-dd.kxpq.de) wegen einer Lösung nachfragen.

**Comment by genericFJS** [comment]
Alles, was mit /scr/ anfängt hat in der Regel mit dem KOMA-Script package zu tun: https://www.ctan.org/pkg/koma-script?lang=en
Zur not das einfach noch mal komplett installieren. Bei MikTeX (full) ist es dabei.

**Comment by Nos-** [comment]
Das Problem ließe sich möglicherweise mit einem Update meiner TeX-Live Installation beheben. Dieses würde aber leider ein Distributionsupdate nach sich ziehen (nur einzelne Teilpakete zu updaten führt nur zu Abhängigkeitsproblemen).

**Comment by genericFJS** [comment]
In dem Fall wäre es ja kein Problem einfach die entsprechenden Zeilen bezüglich dieses Packages im Header-File rauszunehmen. Soweit ich jetzt denken kann, wird das Paket nur dort (für die Kopf- und Fußzeilen) gebraucht. Nimm doch einfach die Zeile mit dem entsprechenden include raus und dann alle Zeilen, die darauf hin fehler erzeugen (und damit zusammen hängen). Solange du den latex_master und die kompilierten pdfs nicht commitest ist doch alles in ordnung.

**Comment by genericFJS** [comment]
Genau genommen sind das (momentan) folgende Zeilen:
17 und 147-152
Wenn diese auskommentiert werden, lässt es sich auch ohne das scrlayer-package compilieren - es fehlen eben bloß die Kopf- und Fußzeilen.

**Comment by genericFJS** [comment]
Habe dafür mal einen branch erstellt: https://github.com/genericFJS/htw/tree/master_compatibilty

**Comment by Nos-** [comment]
Danke.
